Tests pass silently even with errors
This is because an Exception is getting lost
---
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<__call__() done, defined at
/home/user/github/Distributed-Algorithms/distalg/process.py:14>
exception=TypeError("start() missing 1 required positional argument: 'self'",)>
Traceback (most recent call last):
      File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
          result = coro.send(None)
        File
      "/home/user/github/Distributed-Algorithms/distalg/process.py",
      line 15, in __call__
          await self.func(*args, **kwargs)
      TypeError: start() missing 1 required positional argument: 'self'
---